name: CI - build and test

on:
  push:
    branches: [ main, yml-testing ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate gradle wrapper using official gradle validation action
        uses: gradle/wrapper-validation-action@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build gradle with official gradle build action
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build | test
